name: "SnapDev"
description: "Snapcast Server & Client, librespot and MPD for Radio"
version: "0.6.18"
slug: "snapcast2"
init: false
startup: services
audio: true
ingress: true
ingress_port: 1780
panel_admin: false
host_network: true
arch:
- armhf
- armv7
- aarch64
- amd64
- i386
startup: services
boot: auto
panel_icon: mdi:music
options:
  server:
    enable: true
    buffer_ms: 400
    enable_web: true
    enable_mpd: true
    enable_stream_librespot: true
    librespot_name: Spotify
    librespot_device_name: Snapcast
    librespot_initial_volume: 100
    librespot_bitrate: 160
    librespot_normalize: false
    librespot_killall: false
    librespot_disable_audio_cache: false
    librespot_params: ''
    librespot_extra_params: ''
#    enable_stream_shairport: true
#    shairport_name: Airplay
#    shairport_devicename: Snapcast
#    shairport_params: ''
  client:
    enable: true
    host: localshost
    extra_params: '--logsink=null --logfilter=*:fatal'
schema:
  server:
    enable: bool
    buffer_ms: int
    enable_web: bool
    enable_mpd: bool
    enable_stream_librespot: bool
    librespot_name: str?
    librespot_device_name: str?
    librespot_initial_volume: int(0,100)?
    librespot_bitrate: list(96|160|320)?
    librespot_normalize: bool?
    librespot_killall: bool?
    librespot_disable_audio_cache: bool?
    librespot_params: str?
    librespot_extra_params: str?
    custom_streams: str?
#    enable_stream_shairport: bool
#    shairport_name: str?
#    shairport_devicename: str?
#    shairport_params: str?
  client:
    enable: bool
    host: str
    port: port?
    extra_params: str?
